const ACTION_TYPES = {
    API_PENDING: 'SERVICE_PENDING',
    API_SUCCESS: 'SERVICE_SUCCESS',
    API_GENRES: 'SERVICE_GENRES',
    API_DETAILS: 'SERVICE_DETAILS',
    API_CREDITS: 'SERVICE_CREDITS',
    API_ERROR: 'SERVICE_ERROR',
}
export default ACTION_TYPES